server:
    port: 5050

spring :
    datasource:
        url: jdbc:h2:mem:testdb
        username : sa
        password : password
        driverClassName : org.h2.Driver
        show-sql : true
        dll-auto : update
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console.enabled: true
jwt :
    secret : asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4
    expirationDateInMs : 18000000